name: flutter_ume_kit_ecosed
description: "flutter_ume_kit_ecosed"
version: 0.0.1
homepage: https://github.com/libecosed/flutter_ume_kit_ecosed

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ">=1.0.0 <2.0.0"
  ecosed_kit:
    path: ../EcosedKit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
